networks:
  locale:
    driver: bridge
    name: locale
volumes:
  asterisk_volume:
services:
  mockasterisk:
    image: ${REGISTRY}/${ORG}/${CONTAINER_NAME}:${VERSION}
    container_name: ${CONTAINER_NAME}
    build:
      dockerfile: Dockerfile
      context: "."
    ports:
      - 2031:22
    networks:
      - locale
    volumes:
     - ./extensions.conf:/etc/asterisk/extensions.conf
     - ./pjsip.conf:/etc/asterisk/pjsip.conf
     - /root/.ssh:/root/.ssh
    restart: always